"""post

Revision ID: 12deea574a19
Revises: 40295442ae92
Create Date: 2023-05-30 09:57:48.842254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12deea574a19'
down_revision = '40295442ae92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Followers')
    op.drop_table('Quick')
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_user_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birth_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('followers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nick_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='Users_pkey'),
    sa.UniqueConstraint('email', name='Users_email_key'),
    sa.UniqueConstraint('nick_name', name='Users_nick_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Quick',
    sa.Column('quick_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Quick_quick_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['by'], ['Users.nick_name'], name='Quick_by_fkey'),
    sa.PrimaryKeyConstraint('quick_id', name='Quick_pkey')
    )
    op.create_table('Followers',
    sa.Column('follow_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Followers_follow_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['Users.user_id'], name='Followers_follower_id_fkey'),
    sa.ForeignKeyConstraint(['user_followed_id'], ['Users.user_id'], name='Followers_user_followed_id_fkey'),
    sa.PrimaryKeyConstraint('follow_id', name='Followers_pkey')
    )
    # ### end Alembic commands ###
